language: c
arch:
  - amd64
  - arm64
os:
  - linux
  - osx
compiler:
  - gcc
  - clang
matrix:
  exclude:
    - os: osx
      compiler: gcc
  include:
    - os: osx
      osx_image: xcode11
      compiler: gcc-9
script:
  - mkdir build
  - cd build
  - cmake ..
  - make && make test
